theme: jekyll-theme-midnight
title: Hyosup-Kim's Devlog
tagline: South Korea, Now on Military Service
description: This is personal blog that I post about my study and projects.
author: Hyosup-Kim

timezone: Asia/Seoul



